trigger:
 branches:
   include:
     - main
     - feature/*

pool: infra_pool     

jobs:
- job: Terraforminitplan
  displayName: Terraforminit,fmt,validate and plan
  pool: infra_pool

  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.5.7'

  
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
      backendServiceArm: 'infra_connection'
      backendAzureRmResourceGroupName: 'paras_rg'
      backendAzureRmStorageAccountName: 'parasstg'
      backendAzureRmContainerName: 'devcont'
      backendAzureRmKey: 'dev.terraform.tfstate'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'custom'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
      outputTo: 'console'
      customCommand: 'fmt'
      environmentServiceNameAzureRM: 'infra_connection'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
      environmentServiceNameAzureRM: 'infra_connection'

- job: TFSec_Scanner
  displayName: tfsecScanner
  dependsOn: Terraforminitplan

  steps:
  - task: tfsec@1
    inputs:
      version: 'v1.26.0'

- job: Terraform_apply
  displayName: Terraform Apply
  dependsOn: TFSec_Scanner

  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.5.7'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'''
      backendServiceArm: 'infra_connection'
      backendAzureRmResourceGroupName: 'paras_rg'
      backendAzureRmStorageAccountName: 'parasstg'
      backendAzureRmContainerName: 'devcont'
      backendAzureRmKey: 'dev.terraform.tfstate'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/dev'
      environmentServiceNameAzureRM: 'infra_connection'

  
     

